<?php

namespace Database\Seeders;

use App\Models\CommunityCluster;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CommunityClusterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clusters = [
            ['name' => 'A', 'community_id' => '1'],
            ['name' => 'B', 'community_id' => '1'],
            ['name' => 'C', 'community_id' => '1'],
            ['name' => 'D', 'community_id' => '1'],
            ['name' => 'E', 'community_id' => '1'],
            ['name' => 'A', 'community_id' => '2'],
            ['name' => 'B', 'community_id' => '2'],
            ['name' => 'C', 'community_id' => '2'],
            ['name' => 'D', 'community_id' => '2'],
            ['name' => 'E', 'community_id' => '2'],
            ['name' => 'A', 'community_id' => '3'],
            ['name' => 'B', 'community_id' => '3'],
            ['name' => 'C', 'community_id' => '3'],
            ['name' => 'D', 'community_id' => '3'],
            ['name' => 'E', 'community_id' => '3'],
            ['name' => 'A', 'community_id' => '4'],
            ['name' => 'B', 'community_id' => '4'],
            ['name' => 'C', 'community_id' => '4'],
            ['name' => 'D', 'community_id' => '4'],
            ['name' => 'E', 'community_id' => '4'],
            ['name' => 'A', 'community_id' => '5'],
            ['name' => 'B', 'community_id' => '5'],
            ['name' => 'C', 'community_id' => '5'],
            ['name' => 'D', 'community_id' => '5'],
            ['name' => 'E', 'community_id' => '5'],
            ['name' => 'A', 'community_id' => '6'],
            ['name' => 'B', 'community_id' => '6'],
            ['name' => 'C', 'community_id' => '6'],
            ['name' => 'D', 'community_id' => '6'],
            ['name' => 'E', 'community_id' => '6'],
            ['name' => 'A', 'community_id' => '7'],
            ['name' => 'B', 'community_id' => '7'],
            ['name' => 'C', 'community_id' => '7'],
            ['name' => 'D', 'community_id' => '7'],
            ['name' => 'E', 'community_id' => '7'],
            ['name' => 'A', 'community_id' => '8'],
            ['name' => 'B', 'community_id' => '8'],
            ['name' => 'C', 'community_id' => '8'],
            ['name' => 'D', 'community_id' => '8'],
            ['name' => 'E', 'community_id' => '8'],
            ['name' => 'A', 'community_id' => '9'],
            ['name' => 'B', 'community_id' => '9'],
            ['name' => 'C', 'community_id' => '9'],
            ['name' => 'D', 'community_id' => '9'],
            ['name' => 'E', 'community_id' => '9'],
            ['name' => 'A', 'community_id' => '10'],
            ['name' => 'B', 'community_id' => '10'],
            ['name' => 'C', 'community_id' => '10'],
            ['name' => 'D', 'community_id' => '10'],
            ['name' => 'E', 'community_id' => '10'],
            ['name' => 'A', 'community_id' => '11'],
            ['name' => 'B', 'community_id' => '11'],
            ['name' => 'C', 'community_id' => '11'],
            ['name' => 'D', 'community_id' => '11'],
            ['name' => 'E', 'community_id' => '11'],
            ['name' => 'A', 'community_id' => '12'],
            ['name' => 'B', 'community_id' => '12'],
            ['name' => 'C', 'community_id' => '12'],
            ['name' => 'D', 'community_id' => '12'],
            ['name' => 'E', 'community_id' => '12'],
            ['name' => 'A', 'community_id' => '13'],
            ['name' => 'B', 'community_id' => '13'],
            ['name' => 'C', 'community_id' => '13'],
            ['name' => 'D', 'community_id' => '13'],
            ['name' => 'E', 'community_id' => '13'],
            ['name' => 'A', 'community_id' => '14'],
            ['name' => 'B', 'community_id' => '14'],
            ['name' => 'C', 'community_id' => '14'],
            ['name' => 'D', 'community_id' => '14'],
            ['name' => 'E', 'community_id' => '14'],
            ['name' => 'A', 'community_id' => '15'],
            ['name' => 'B', 'community_id' => '15'],
            ['name' => 'C', 'community_id' => '15'],
            ['name' => 'D', 'community_id' => '15'],
            ['name' => 'E', 'community_id' => '15'],
            ['name' => 'A', 'community_id' => '16'],
            ['name' => 'B', 'community_id' => '16'],
            ['name' => 'C', 'community_id' => '16'],
            ['name' => 'D', 'community_id' => '16'],
            ['name' => 'E', 'community_id' => '16'],
            ['name' => 'A', 'community_id' => '17'],
            ['name' => 'B', 'community_id' => '17'],
            ['name' => 'C', 'community_id' => '17'],
            ['name' => 'D', 'community_id' => '17'],
            ['name' => 'E', 'community_id' => '17'],
            ['name' => 'A', 'community_id' => '18'],
            ['name' => 'B', 'community_id' => '18'],
            ['name' => 'C', 'community_id' => '18'],
            ['name' => 'D', 'community_id' => '18'],
            ['name' => 'E', 'community_id' => '18'],
            ['name' => 'A', 'community_id' => '19'],
            ['name' => 'B', 'community_id' => '19'],
            ['name' => 'C', 'community_id' => '19'],
            ['name' => 'D', 'community_id' => '19'],
            ['name' => 'E', 'community_id' => '19'],
            ['name' => 'A', 'community_id' => '20'],
            ['name' => 'B', 'community_id' => '20'],
            ['name' => 'C', 'community_id' => '20'],
            ['name' => 'D', 'community_id' => '20'],
            ['name' => 'E', 'community_id' => '20'],
            ['name' => 'A', 'community_id' => '21'],
            ['name' => 'B', 'community_id' => '21'],
            ['name' => 'C', 'community_id' => '21'],
            ['name' => 'D', 'community_id' => '21'],
            ['name' => 'E', 'community_id' => '21'],
            ['name' => 'A', 'community_id' => '22'],
            ['name' => 'B', 'community_id' => '22'],
            ['name' => 'C', 'community_id' => '22'],
            ['name' => 'D', 'community_id' => '22'],
            ['name' => 'E', 'community_id' => '22'],
            ['name' => 'A', 'community_id' => '23'],
            ['name' => 'B', 'community_id' => '23'],
            ['name' => 'C', 'community_id' => '23'],
            ['name' => 'D', 'community_id' => '23'],
            ['name' => 'E', 'community_id' => '23'],
        ];

        CommunityCluster::insert($clusters);
    }
}
