<?php

namespace Database\Seeders;

use App\Models\Designation;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DesignationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $designations = [
            ['name' => 'Engineer'], 
            ['name' => 'Teacher'], 
            ['name' => 'Retired'], 
            ['name' => 'Housewife'], 
            ['name' => 'Service'], 
            ['name' => 'Student'], 
            ['name' => 'Hotel Manager'], 
            ['name' => 'Lecturer'], 
            ['name' => 'Handicapped'], 
            ['name' => 'Instructor'], 
            ['name' => 'Self Employed'], 
            ['name' => 'Taxi Driver'], 
            ['name' => 'Abroad'], 
            ['name' => 'Ship'], 
            ['name' => 'Sr. Citizen'], 
            ['name' => 'Tution'], 
            ['name' => 'Housemaid'], 
            ['name' => 'Secretary'], 
            ['name' => 'Christian Brother'], 
            ['name' => 'Internship'], 
            ['name' => 'Unemployed'], 
            ['name' => 'Consultant'], 
            ['name' => 'Mechanic'], 
            ['name' => 'Nurse'], 
            ['name' => 'Business'], 
            ['name' => 'LIC Agent'], 
            ['name' => 'Civil Contractor'], 
            ['name' => 'Technician'], 
            ['name' => 'Tailor'], 
            ['name' => 'Designer'], 
            ['name' => 'Sheltered Workshop'], 
            ['name' => 'Driver'], 
            ['name' => 'Railways'], 
            ['name' => 'Typist'], 
            ['name' => 'Telephone Operator'], 
            ['name' => 'Merchant Officer'], 
            ['name' => 'Child'], 
            ['name' => 'Musician'], 
            ['name' => 'Chef'], 
            ['name' => 'Physiotherapist'], 
            ['name' => 'Catering'], 
            ['name' => 'Carpenter'], 
            ['name' => 'Receptionist'], 
            ['name' => 'VRS'], 
            ['name' => 'Phy. Educator'], 
            ['name' => 'Spl. Educator'], 
            ['name' => 'Social Worker'], 
            ['name' => 'Chartered Accountant'], 
            ['name' => 'Mariner'], 
            ['name' => 'Journalist'], 
            ['name' => 'Pathologist'], 
            ['name' => 'Cooking Orders'], 
            ['name' => 'AC Operator'], 
            ['name' => 'Estate Agent'], 
            ['name' => 'Advocate'], 
            ['name' => 'Mill Worker'], 
            ['name' => 'Part-time'], 
            ['name' => 'Accountant'], 
            ['name' => 'Homebound'], 
            ['name' => 'Call Center'], 
            ['name' => 'Steward'], 
            ['name' => 'Priest'], 
            ['name' => 'Professor'], 
            ['name' => 'Computer'], 
            ['name' => 'Manager'], 
            ['name' => 'Principal'], 
            ['name' => 'Priesthood'], 
            ['name' => 'P.Assistant'], 
            ['name' => 'Draughtsman'], 
            ['name' => 'Helper'], 
            ['name' => 'Domestic worker'], 
            ['name' => 'Compounder'], 
            ['name' => 'Advisor'], 
            ['name' => 'HR Executive'], 
            ['name' => 'Nun'], 
            ['name' => 'Electrician'], 
            ['name' => 'Dentist'], 
            ['name' => 'Reporter'], 
            ['name' => 'Wireman'], 
            ['name' => 'Fitter'], 
            ['name' => 'Florist'], 
            ['name' => 'Photographer'], 
            ['name' => 'Beautician'], 
            ['name' => 'Psychologist'], 
            ['name' => 'Media'], 
            ['name' => 'Babysitting'], 
            ['name' => 'Niece\'s son'], 
            ['name' => 'Doctor'], 
            ['name' => 'Gynaecologist'], 
            ['name' => 'Navy'], 
            ['name' => 'Architect'], 
            ['name' => 'Pensioner'], 
            ['name' => 'Masseur'], 
            ['name' => 'Clerk'], 
            ['name' => 'Turner'], 
            ['name' => 'Welder'], 
            ['name' => 'Airhostess'], 
            ['name' => 'Seminarian'], 
            ['name' => 'Lawyer'], 
            ['name' => 'Executive'], 
            ['name' => 'Marketing'], 
            ['name' => 'Spl. Child'] 
            ];

        Designation::insert($designations);
    }
}
