<?php

namespace Database\Seeders;

use App\Models\Parish;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ParishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $parishes = [
            ['deanery' => 'Thane', 'name' => 'Our Lady of Perpetual Succour', 'code' => 'OLPS3', 'address' => 'Block No A-528, Room No 1056, Ulhasnagar, Dt. Thane 421004'], 
            ['deanery' => 'South Mumbai', 'name' => 'Cathedral of the Holy Name', 'code' => 'CHN1', 'address' => '19, Nathalal Parekh Marg, Mumbai 400 001'], 
            ['deanery' => 'South Mumbai', 'name' => 'Our Lady of Health', 'code' => 'OLH3', 'address' => 'Dr. Viegas Street, Cavel, Mumbai 400 002'], 
            ['deanery' => 'South Mumbai', 'name' => 'Our Lady of Glory', 'code' => 'OLG1', 'address' => 'Sant Savta Marg, Byculla, Mumbai 400 027'], 
            ['deanery' => 'South Mumbai', 'name' => 'St Stephen', 'code' => 'SS2', 'address' => '1, L. Jagmohandas Marg, Cumballa Hill, Mumbai 400036'], 
            ['deanery' => 'South Mumbai', 'name' => 'St Joseph', 'code' => 'SJ9', 'address' => 'Robert Road, Colaba, Mumbai 400 005'], 
            ['deanery' => 'South Mumbai', 'name' => 'St Francis Xavier', 'code' => 'SFX4', 'address' => 'St. Francis Xavier Street, Thakurdwar, Dabul, Mumbai 400 002'], 
            ['deanery' => 'South Mumbai', 'name' => 'St John the Evangelist', 'code' => 'SJE2', 'address' => '8, Dr Sunderlal Bahl Path, Ballard Estate, Fort, Mumbai 400001'], 
            ['deanery' => 'South Mumbai', 'name' => 'St Teresa', 'code' => 'ST3', 'address' => '252, Rajaram Mohan Roy Road, Girgaum, Mumbai 400 004'], 
            ['deanery' => 'South Mumbai', 'name' => 'St Ignatius', 'code' => 'SI2', 'address' => '203, Kazi Syed Street, Mandvi, Mumbai 400 003'], 
            ['deanery' => 'South Mumbai', 'name' => 'Our Lady of the Rosary', 'code' => 'OLR3', 'address' => 'Dockyard Road, Mazagaon, Mumbai 400 010'], 
            ['deanery' => 'South Mumbai', 'name' => 'St Anne', 'code' => 'SA9', 'address' => 'Dhody Marg, Mazagaon, Mumbai 400 010'], 
            ['deanery' => 'South Mumbai', 'name' => 'Our Lady of Dolours', 'code' => 'OLD2', 'address' => 'Dr. Cawasji Hormusji Street, New Sonapur, Marine Lines, Mumbai 400 002'], 
            ['deanery' => 'South Mumbai', 'name' => 'St Joseph', 'code' => 'SJ10', 'address' => 'St Joseph Chowk, Nowrojee Hill Road No.5, Umerkhadi, Mumbai 400 009'], 
            ['deanery' => 'North Mumbai', 'name' => 'St Paul', 'code' => 'SP2', 'address' => '205, Dr. Ambedkar Road, Dadar, Mumbai 400 014'], 
            ['deanery' => 'North Mumbai', 'name' => 'Our Lady of Salvation', 'code' => 'OLS3', 'address' => 'S.K. Bole Road, Dadar, Mumbai 400 028'], 
            ['deanery' => 'North Mumbai', 'name' => 'St Anthony', 'code' => 'SA8', 'address' => 'Plot No. 890C, Dharavi Main Road, Near Post Office, Dharavi, Mumbai 400 017'], 
            ['deanery' => 'North Mumbai', 'name' => 'St Ignatius', 'code' => 'SI1', 'address' => 'Sane Guruji Road, Jacob Circle, Mumbai 400 011'], 
            ['deanery' => 'North Mumbai', 'name' => 'Holy Cross', 'code' => 'HC3', 'address' => 'Senapati Bapat Marg, Lower Parel, Mumbai 400 013'], 
            ['deanery' => 'North Mumbai', 'name' => 'Our Lady of Victories', 'code' => 'OLV2', 'address' => 'Lady Jamshedji Road, Mahim, Mumbai 400 016'], 
            ['deanery' => 'North Mumbai', 'name' => 'St Michael', 'code' => 'SM1', 'address' => 'Lady Jamshedji Road, Mahim, Mumbai 400 016'], 
            ['deanery' => 'North Mumbai', 'name' => 'Our Lady of Fatima', 'code' => 'OLF4', 'address' => 'Golanji Hill Road, Sewri, Mumbai 400 015'], 
            ['deanery' => 'North Mumbai', 'name' => 'Our Lady of Good Counsel', 'code' => 'OLGC1', 'address' => 'Sion, Near Railway Station, Mumbai 400 022'], 
            ['deanery' => 'North Mumbai', 'name' => 'Our Lady of Lourdes', 'code' => 'OLL3', 'address' => 'Bhaudaji Extension Road, Sion, Mumbai 400 022'], 
            ['deanery' => 'North Mumbai', 'name' => 'St Dominic Savio', 'code' => 'SDS1', 'address' => 'Wadala East, Mumbai 400 037'], 
            ['deanery' => 'North Mumbai', 'name' => 'Our Lady of Dolours', 'code' => 'OLD1', 'address' => 'David Barretto Road, Wadala, Mumbai 400 031'], 
            ['deanery' => 'North Mumbai', 'name' => 'Sacred Heart', 'code' => 'SH4', 'address' => '26, Sasmira Marg, Worli, Mumbai 400 030'], 
            ['deanery' => 'Bandra', 'name' => 'St Joseph the Worker', 'code' => 'SJW1', 'address' => 'Bandra East, Mumbai 400 051'], 
            ['deanery' => 'Bandra', 'name' => 'Our Lady of Mount Carmel', 'code' => 'OLMC1', 'address' => '81A, Chapel Road, Bandra, Mumbai 400050'], 
            ['deanery' => 'Bandra', 'name' => 'St Andrew', 'code' => 'SA1', 'address' => '115, Hill Road, Bandra, Mumbai 400 050'], 
            ['deanery' => 'Bandra', 'name' => 'St Anne', 'code' => 'SA2', 'address' => 'Pali Hill, Nargis Dutt Road, Bandra (West), Mumbai, Maharashtra 400050'], 
            ['deanery' => 'Bandra', 'name' => 'St Francis of Assisi', 'code' => 'SFA1', 'address' => 'Kadeshwari Marg, Bandra, Mumbai 400 050'], 
            ['deanery' => 'Bandra', 'name' => 'St Peter', 'code' => 'SP1', 'address' => 'Hill Road, Bandra, Mumbai 400 050'], 
            ['deanery' => 'Bandra', 'name' => 'St Theresa', 'code' => 'ST1', 'address' => 'St Theresa Marg, T.P.S. III, Bandra, Mumbai 400 050'], 
            ['deanery' => 'Bandra', 'name' => 'St Vincent De Paul', 'code' => 'SVDP1', 'address' => 'St Vincent De Paul Church, 20th Road, Khar West, Mumbai 400 052'], 
            ['deanery' => 'Central Suburbs', 'name' => 'Our Lady of Health of Velankanni', 'code' => 'OLHV1', 'address' => 'Society Road, Irla, Mumbai 400 056'], 
            ['deanery' => 'Central Suburbs', 'name' => 'St Joseph', 'code' => 'SJ5', 'address' => 'Juhu, Mumbai 400 049'], 
            ['deanery' => 'Central Suburbs', 'name' => 'Holy Cross', 'code' => 'HC1', 'address' => 'Gawde Road, Juhu-Tara, Mumbai 400 049'], 
            ['deanery' => 'Central Surburbs', 'name' => 'Our Lady of Egypt', 'code' => 'OLE1', 'address' => 'Kalina, Santa Cruz East, Mumbai 400 029'], 
            ['deanery' => 'Central Suburbs', 'name' => 'Sacred Heart', 'code' => 'SH2', 'address' => 'Swami Vivekanand Road, Santa Cruz West, Mumbai 400 054'], 
            ['deanery' => 'Central Suburbs', 'name' => 'St Anthony', 'code' => 'SA5', 'address' => 'Vakola, Santa Cruz East, Mumbai 400 055'], 
            ['deanery' => 'Central Suburbs', 'name' => 'St Francis Xavier', 'code' => 'SFX1', 'address' => 'Church Road, Vile Parle West, Mumbai 400 056'], 
            ['deanery' => 'Andheri', 'name' => 'Holy Family', 'code' => 'HF1', 'address' => 'Andheri East, Mumbai 400093'], 
            ['deanery' => 'Andheri', 'name' => 'Sacred Heart', 'code' => 'SH1', 'address' => 'Mahakali Road, Andheri East, Mumbai 400 093'], 
            ['deanery' => 'Andheri', 'name' => 'Good Shepherd', 'code' => 'GS1', 'address' => 'Four Bungalows Road, Andheri West, Mumbai 400 053'], 
            ['deanery' => 'Andheri', 'name' => 'St Blaise', 'code' => 'SB1', 'address' => 'Caesar Road, Amboli, Andheri West, Mumbai 400 058'], 
            ['deanery' => 'Andheri', 'name' => 'Infant Jesus', 'code' => 'IJ1', 'address' => 'Off Western Express Highway, Shankarwadi, Jogeshwari East, Mumbai 400 060'], 
            ['deanery' => 'Andheri', 'name' => 'Christ the King', 'code' => 'CK1', 'address' => 'Kranti Nagar, Behram Baug Road, Oshiwara, Jogeshwari West, Mumbai 400 102'], 
            ['deanery' => 'Andheri', 'name' => 'St John the Evangelist', 'code' => 'SJE1', 'address' => 'Church Road, Marol, Andheri East, Mumbai 400 059'], 
            ['deanery' => 'Andheri', 'name' => 'St Vincent Pallotti', 'code' => 'SVP1', 'address' => 'Vijay Nagar, Marol-Maroshi Road, Mumbai 400 059'], 
            ['deanery' => 'Andheri', 'name' => 'Our Lady of Health', 'code' => 'OLH1', 'address' => 'New International Cargo Complex, Sahar, Andheri East, Mumbai 400 099'], 
            ['deanery' => 'Andheri', 'name' => 'Our Lady of Health', 'code' => 'OLH2', 'address' => 'Yari Road, Versova, Andheri West, Mumbai 400 061'], 
            ['deanery' => 'Borivli', 'name' => 'Christ the King', 'code' => 'CK2', 'address' => '102, Namrata Building, 1st floor, Odhav Nagar, Borivli East, Mumbai 400 066'], 
            ['deanery' => 'Borivli', 'name' => 'Our Lady of the Immaculate Conception', 'code' => 'OLIC1', 'address' => 'Mt. Poinsur, Borivli West, Mumbai 400 103'], 
            ['deanery' => 'Borivli', 'name' => 'St John Bosco', 'code' => 'SJB1', 'address' => 'Vazira Naka, L.T. Road, Borivli West, Mumbai 400 091'], 
            ['deanery' => 'Borivli', 'name' => 'St Louis', 'code' => 'SL1', 'address' => 'Near Old Bridge, Y.T. Road, Dahisar West, Mumbai 400 068'], 
            ['deanery' => 'Borivli', 'name' => 'St Joseph', 'code' => 'SJ3', 'address' => '002, A/46, Prashant, Sai Road, Gokuldham, Goregaon East, Mumbai 400 063'], 
            ['deanery' => 'Borivli', 'name' => 'St Thomas', 'code' => 'ST2', 'address' => 'Church Road, Goregaon East, Mumbai 400 063'], 
            ['deanery' => 'Borivli', 'name' => 'Our Lady of the Rosary', 'code' => 'OLR1', 'address' => 'Mahatma Gandhi Road, Goregaon West, Mumbai 400 062'], 
            ['deanery' => 'Borivli', 'name' => 'Nativity of Our Lord', 'code' => 'NOL1', 'address' => 'C.T.S. 169, Akurli Road, Opp. Mahindra Yellow Gate, Kandivli East, Mumbai 400 101'], 
            ['deanery' => 'Borivli', 'name' => 'Our Lady of the Assumption', 'code' => 'OLA1', 'address' => 'Dahanukarwadi, Mahatma Gandhi Road, Kandivli West, Mumbai 400 067'], 
            ['deanery' => 'Borivli', 'name' => 'Our Lady of the Sea', 'code' => 'OLS2', 'address' => 'Madh Island, Malad, Mumbai 400 095'], 
            ['deanery' => 'Borivli', 'name' => 'St Jude', 'code' => 'SJ4', 'address' => 'Vaishet Pada, Triveni Nagar, Malad East, Mumbai, Maharashtra 400 097'], 
            ['deanery' => 'Borivli', 'name' => 'Our Lady of Lourdes', 'code' => 'OLL2', 'address' => 'Marve Road, Orlem, Malad West, Mumbai 400 064'], 
            ['deanery' => 'Borivli', 'name' => 'St Anthony', 'code' => 'SA4', 'address' => 'Malwani, Malad West, Mumbai 400 095'], 
            ['deanery' => 'Borivli', 'name' => 'Our Lady of the Forsaken', 'code' => 'OLF1', 'address' => 'Off Malad-Marve Road, Block 7, Malwani Colony, Mumbai 400 095'], 
            ['deanery' => 'Borivli', 'name' => 'Our Lady of Remedy', 'code' => 'OLR2', 'address' => 'Poinsur, P.O. Kandivli, Mumbai 400 067'], 
            ['deanery' => 'Kurla', 'name' => 'Mother Vellankanni', 'code' => 'MV1', 'address' => 'Sector 1, Jacob Johnson Marg, Near BMC Ground, Cheetah Camp, Mumbai 400 088'], 
            ['deanery' => 'Kurla', 'name' => 'Our Lady of Perpetual Succour', 'code' => 'OLPS2', 'address' => 'St Anthony Road, Chembur, Mumbai 400 071'], 
            ['deanery' => 'Kurla', 'name' => 'Infant Jesus', 'code' => 'IJ2', 'address' => 'Pant Nagar,Ghatkopar East, Mumbai 400 075'], 
            ['deanery' => 'Kurla', 'name' => 'St Jude', 'code' => 'SJ6', 'address' => 'M.V. Marg, Andheri-Kurla Road, Jeri-Meri, Mumbai 400 072'], 
            ['deanery' => 'Kurla', 'name' => 'Our Lady of Fatima', 'code' => 'OLF2', 'address' => 'P.B. 9237, Kirol, Vidyavihar, Mumbai 400 086'], 
            ['deanery' => 'Kurla', 'name' => 'Holy Cross', 'code' => 'HC2', 'address' => 'Fr Peter Pereira Marg, Kurla, Mumbai 400 070'], 
            ['deanery' => 'Kurla', 'name' => 'St Joseph', 'code' => 'SJ7', 'address' => 'New Mill Road, Kurla West, Mumbai 400 070'], 
            ['deanery' => 'Kurla', 'name' => 'St Anthony', 'code' => 'SA6', 'address' => 'Mankhurd, P.O. Deonar, Mumbai 400 088'], 
            ['deanery' => 'Kurla', 'name' => 'St Sebastian', 'code' => 'SS1', 'address' => 'Mahul Road, Marouli, Mumbai 400 074'], 
            ['deanery' => 'Kurla', 'name' => 'Holy Family', 'code' => 'HF2', 'address' => 'Pestom Sagar, Road No.4, P.O. Tilaknagar, Chembur, Mumbai 400 089'], 
            ['deanery' => 'Kurla', 'name' => 'St Anthony', 'code' => 'SA7', 'address' => 'Kherani Road, Saki Naka, Mumbai 400 072'], 
            ['deanery' => 'Thane', 'name' => 'Our Lady of Fatima', 'code' => 'OLF6', 'address' => 'Satchit, Ambernath West, Dt. Thane 421 505'], 
            ['deanery' => 'Thane', 'name' => 'St Francis Xavier', 'code' => 'SFX5', 'address' => 'D\'Souza Garden,Rameshwadi, Badlapur West, Dt. Thane 421 503'], 
            ['deanery' => 'Thane', 'name' => 'Infant Jesus', 'code' => 'IJ3', 'address' => 'Ganesh Nagar, Dombivli West, Dt.Thane 421 202'], 
            ['deanery' => 'Thane', 'name' => 'St Anthony of Padua', 'code' => 'SAP1', 'address' => 'Sushila Buildings, Block B/6, 2nd floor, Vikram Nagar, Kalwa, Dt. Thane 400 605'], 
            ['deanery' => 'Thane', 'name' => 'Our Lady of Lourdes', 'code' => 'OLL4', 'address' => 'Katemanavli, Kalyan East, Dt. Thane 421 306'], 
            ['deanery' => 'Thane', 'name' => 'Our Lady of Lourdes', 'code' => 'OLL5', 'address' => 'Murbad Road, Kalyan West, Dt. Thane 421 301'], 
            ['deanery' => 'Thane', 'name' => 'St Francis Xavier', 'code' => 'SFX6', 'address' => 'Church Road, Kanjurmarg East, Mumbai 400 042'], 
            ['deanery' => 'Thane', 'name' => 'Our Lady of Fatima', 'code' => 'OLF7', 'address' => 'Opp. Municipal Office, Majiwada, Dt. Thane 400 601'], 
            ['deanery' => 'Thane', 'name' => 'St Pius X', 'code' => 'SPX1', 'address' => 'Mulund West, Mumbai 400 080'], 
            ['deanery' => 'Thane', 'name' => 'St Joseph', 'code' => 'SJ11', 'address' => 'Behind Mumbra Police Station, Near Shanti Nagar, Anand Koliwada, Mumbra, Dt. Thane 400 612'], 
            ['deanery' => 'Thane', 'name' => 'St Francis Xavier', 'code' => 'SFX7', 'address' => '4th Road, Parksite, Vikhroli West, Mumbai 400 079'], 
            ['deanery' => 'Thane', 'name' => 'Our Lady of Mercy', 'code' => 'OLM1', 'address' => 'Pokhran Road No.2, Near Blue Star Company, Thane 400 610'], 
            ['deanery' => 'Thane', 'name' => 'Most Holy Trinity', 'code' => 'MHT1', 'address' => 'Near I.I.T. Market, Powai, Mumbai 400 076'], 
            ['deanery' => 'Thane', 'name' => 'St Anthony', 'code' => 'SA10', 'address' => 'Tembipada, Bhandup, Milind Nagar, Tembhipada, Bhandup West, Mumbai, 400 078'], 
            ['deanery' => 'Thane', 'name' => 'St John the Baptist', 'code' => 'SJB2', 'address' => 'Jambli Naka, L.B.S. Marg, Thane 400 601'], 
            ['deanery' => 'Thane', 'name' => 'St Joseph', 'code' => 'SJ12', 'address' => 'Station Road, Vikhroli West, Mumbai 400 079'], 
            ['deanery' => 'Thane', 'name' => 'St Lawrence', 'code' => 'SL2', 'address' => 'Vasudev Balwant Phadke Road, D\'Souza Wadi, Wagle Estate, Dt. Thane 400 604'], 
            ['deanery' => 'Bhayandar', 'name' => 'Divine Mercy', 'code' => 'DM1', 'address' => 'Ramdev Park Road, Near Ostwal Avenue Bhayandar East, Dt. Thane 401 105'], 
            ['deanery' => 'Bhayandar', 'name' => 'Our Lady of Nazareth', 'code' => 'OLN1', 'address' => 'Near Mira BHAYANDAR Nagarpalika, Bhayandar, Dt. Thane 401 101'], 
            ['deanery' => 'Bhayandar', 'name' => 'St Andrew', 'code' => 'SA3', 'address' => 'Dongri-Chowk, P.O. Uttan, Dt. Thane 401 106'], 
            ['deanery' => 'Bhayandar', 'name' => 'Our Lady of Bethlehem', 'code' => 'OLB1', 'address' => 'Dongri, via Bhayandar, Dt. Thane 401 106'], 
            ['deanery' => 'Bhayandar', 'name' => 'Holy Magi', 'code' => 'HM1', 'address' => 'Gorai village (Beyond the Creek), P.O. Borivli, Mumbai 400 091'], 
            ['deanery' => 'Bhayandar', 'name' => 'St Jerome', 'code' => 'SJ1', 'address' => 'P.O. Mira, Kashimira, Dt. Thane 401 104'], 
            ['deanery' => 'Bhayandar', 'name' => 'Our Lady of Perpetual Succour', 'code' => 'OLPS1', 'address' => 'Manori, P.O. Kharodi, Mumbai 400 095'], 
            ['deanery' => 'Bhayandar', 'name' => 'St Joseph', 'code' => 'SJ2', 'address' => 'Krista Shanti Dham, St Joseph Chowk, Mira Road East, Dt. Thane 401 107.'], 
            ['deanery' => 'Bhayandar', 'name' => 'Our Lady of the Sea', 'code' => 'OLS1', 'address' => 'Uttan, Bhayandar West, Dt. Thane 401 106'], 
            ['deanery' => 'Bhayandar', 'name' => 'Our Lady of Lourdes', 'code' => 'OLL1', 'address' => 'Uttan-Pali, P.O.Uttan, Dt. Thane 401 106'], 
            ['deanery' => 'Navi Mumbai', 'name' => 'St Theresa of the Child Jesus', 'code' => 'STCJ1', 'address' => 'Plot 24, Sector 10, Airoli, Navi Mumbai 400 708'], 
            ['deanery' => 'Navi Mumbai', 'name' => 'St Joseph', 'code' => 'SJ8', 'address' => 'Plot No.28, Sector 8B, C.B.D.- Belapur, Navi Mumbai 400 614'], 
            ['deanery' => 'Navi Mumbai', 'name' => 'Our Lady of the Forsaken', 'code' => 'OLF3', 'address' => 'Ghansoli Village, Building No. 446, THANE-Belapur Road, Navi Mumbai 400 701'], 
            ['deanery' => 'Navi Mumbai', 'name' => 'Holy Spirit', 'code' => 'HS1', 'address' => 'Plot No.6, Sector 11, Kalamboli, Navi Mumbai 410 218'], 
            ['deanery' => 'Navi Mumbai', 'name' => 'Divya Kripa', 'code' => 'DK1', 'address' => 'Plot No. 7, Sector 5, opp ITM Hostel, Kharghar, Navi Mumbai 410210'], 
            ['deanery' => 'Navi Mumbai', 'name' => 'St Francis De Sales', 'code' => 'SFDS1', 'address' => 'Plot No. 19-B/2 Sector 11, Koparkhairane, Navi Mumbai, 400709'], 
            ['deanery' => 'Navi Mumbai', 'name' => 'Our Lady of the Visitation', 'code' => 'OLV1', 'address' => 'Seawoods West, Sector 42A, Nerul, Navi Mumbai, 400706'], 
            ['deanery' => 'Navi Mumbai', 'name' => 'St Francis Xavier', 'code' => 'SFX2', 'address' => 'Behind Orion Mall (McDonald\'s side) & S.T. Depot, Near Samrat Hotel, Panvel 410206'], 
            ['deanery' => 'Navi Mumbai', 'name' => 'Christ the King', 'code' => 'CK4', 'address' => 'Vishwadeep Nagar, Reeswadi, Mohopada Post, Rasayani, Dt. Raigad 410 222'], 
            ['deanery' => 'Navi Mumbai', 'name' => 'Good Shepherd', 'code' => 'GS2', 'address' => 'Plot No 51, Sector 5, Sanpada East, Navi Mumbai 400705'], 
            ['deanery' => 'Navi Mumbai', 'name' => 'Our Lady of the Purification', 'code' => 'OLP1', 'address' => 'Gandhi Chowk, Rajpal Naka, Uran, Navi Mumbai, Raigad 400702'], 
            ['deanery' => 'Navi Mumbai', 'name' => 'Sacred Heart', 'code' => 'SH3', 'address' => 'Plot 67, Sector 9A, Vashi, Navi Mumbai 400 703'], 
            ['deanery' => 'Raigad', 'name' => 'Mary of Nazareth', 'code' => 'MN1', 'address' => 'Chendre, Bypass Road, Near Petrol Pump, Alibag, Dt. Raigad 402 201'], 
            ['deanery' => 'Raigad', 'name' => 'Our Lady of Fatima', 'code' => 'OLF5', 'address' => 'Karjat West, Dt. Raigad 410 201'], 
            ['deanery' => 'Raigad', 'name' => 'Holy Redeemer', 'code' => 'HR1', 'address' => 'Bhanwaj Road, Khopoli, Khalapur Taluka, Dt. Raigad 410 203'], 
            ['deanery' => 'Raigad', 'name' => 'Our Lady of Mount Carmel', 'code' => 'OLMC2', 'address' => 'Korlai, via Revdanda, Dt. Raigad 402 202'], 
            ['deanery' => 'Raigad', 'name' => 'St Francis Xavier', 'code' => 'SFX3', 'address' => 'Jankalyan Trust, Sunderwadi, P.O. Box 7, P.O. Mahad, Dt. Raigad 402 301'], 
            ['deanery' => 'Raigad', 'name' => 'Sacred Heart', 'code' => 'SH5', 'address' => 'Next to Varse Panchayat Office, P.O. Varse, Roha Taluka, Dt. Raigad, 402 116'], 
            ['deanery' => 'Kurla', 'name' => 'Christ the King', 'code' => 'CK3', 'address' => 'Plot No. 46, P.O.Shivaji Nagar, Govandi, Mumbai 400043'], 
            ]            ;

        Parish::insert($parishes);
        // Optionally, you can use the factory to create more parishes
    }
}
