<?php

namespace Database\Seeders;

use App\Models\Parish;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ParishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $parishes = [
                        ['deanery'=>'Thane','name'=>'Our Lady of Perpetual Succour','code'=>'421-004','address'=>'Block No A-528, Room No 1056, Ulhasnagar, Dt. Thane 421004'],
                        ['deanery'=>'South Mumbai','name'=>'Cathedral of the Holy Name','code'=>'400-001','address'=>'19, Nathalal Parekh Marg, Mumbai 400001'],
                        ['deanery'=>'South Mumbai','name'=>'Our Lady of Health','code'=>'400-002','address'=>'Dr. Viegas Street, Cavel, Mumbai 400002'],
                        ['deanery'=>'South Mumbai','name'=>'Our Lady of Glory','code'=>'400-027','address'=>'Sant Savta Marg, Byculla, Mumbai 400027'],
                        ['deanery'=>'South Mumbai','name'=>'St Stephen','code'=>'400-036','address'=>'1, L. Jagmohandas Marg, Cumballa Hill, Mumbai 400036'],
                        ['deanery'=>'South Mumbai','name'=>'St Joseph','code'=>'400-005','address'=>'Robert Road, Colaba, Mumbai 400005'],
                        ['deanery'=>'South Mumbai','name'=>'St Francis Xavier','code'=>'400-002','address'=>'St. Francis Xavier Street, Thakurdwar, Dabul, Mumbai 400002'],
                        ['deanery'=>'South Mumbai','name'=>'St John the Evangelist','code'=>'400-001','address'=>'8, Dr Sunderlal Bahl Path, Ballard Estate, Fort, Mumbai 400001'],
                        ['deanery'=>'South Mumbai','name'=>'St Teresa','code'=>'400-004','address'=>'252, Rajaram Mohan Roy Road, Girgaum, Mumbai 400004'],
                        ['deanery'=>'South Mumbai','name'=>'St Ignatius','code'=>'400-003','address'=>'203, Kazi Syed Street, Mandvi, Mumbai 400003'],
                        ['deanery'=>'South Mumbai','name'=>'Our Lady of the Rosary','code'=>'400-010','address'=>'Dockyard Road, Mazagaon, Mumbai 400010'],
                        ['deanery'=>'South Mumbai','name'=>'St Anne','code'=>'400-010','address'=>'Dhody Marg, Mazagaon, Mumbai 400010'],
                        ['deanery'=>'South Mumbai','name'=>'Our Lady of Dolours','code'=>'400-002','address'=>'Dr. Cawasji Hormusji Street, New Sonapur, Marine Lines, Mumbai 400002'],
                        ['deanery'=>'South Mumbai','name'=>'St Joseph','code'=>'400-009','address'=>'St Joseph Chowk, Nowrojee Hill Road No.5, Umerkhadi, Mumbai 400009'],
                        ['deanery'=>'North Mumbai','name'=>'St Paul','code'=>'400-014','address'=>'205, Dr. Ambedkar Road, Dadar, Mumbai 400014'],
                        ['deanery'=>'North Mumbai','name'=>'Our Lady of Salvation','code'=>'400-028','address'=>'S.K. Bole Road, Dadar, Mumbai 400028'],
                        ['deanery'=>'North Mumbai','name'=>'St Anthony','code'=>'400-017','address'=>'Plot No. 890C, Dharavi Main Road, Near Post Office, Dharavi, Mumbai 400017'],
                        ['deanery'=>'North Mumbai','name'=>'St Ignatius','code'=>'400-011','address'=>'Sane Guruji Road, Jacob Circle, Mumbai 400011'],
                        ['deanery'=>'North Mumbai','name'=>'Holy Cross','code'=>'400-013','address'=>'Senapati Bapat Marg, Lower Parel, Mumbai 400013'],
                        ['deanery'=>'North Mumbai','name'=>'Our Lady of Victories','code'=>'400-016','address'=>'Lady Jamshedji Road, Mahim, Mumbai 400016'],
                        ['deanery'=>'North Mumbai','name'=>'St Michael','code'=>'400-016','address'=>'Lady Jamshedji Road, Mahim, Mumbai 400016'],
                        ['deanery'=>'North Mumbai','name'=>'Our Lady of Fatima','code'=>'400-015','address'=>'Golanji Hill Road, Sewri, Mumbai 400015'],
                        ['deanery'=>'North Mumbai','name'=>'Our Lady of Good Counsel','code'=>'400-022','address'=>'Sion, Near Railway Station, Mumbai 400022'],
                        ['deanery'=>'North Mumbai','name'=>'Our Lady of Lourdes','code'=>'400-022','address'=>'Bhaudaji Extension Road, Sion, Mumbai 400022'],
                        ['deanery'=>'North Mumbai','name'=>'St Dominic Savio','code'=>'400-037','address'=>'Wadala East, Mumbai 400037'],
                        ['deanery'=>'North Mumbai','name'=>'Our Lady of Dolours','code'=>'400-031','address'=>'David Barretto Road, Wadala, Mumbai 400031'],
                        ['deanery'=>'North Mumbai','name'=>'Sacred Heart','code'=>'400-030','address'=>'26, Sasmira Marg, Worli, Mumbai 400030'],
                        ['deanery'=>'Bandra','name'=>'St Joseph the Worker','code'=>'400-051','address'=>'Bandra East, Mumbai 400051'],
                        ['deanery'=>'Bandra','name'=>'Our Lady of Mount Carmel','code'=>'400-050','address'=>'81A, Chapel Road, Bandra, Mumbai 400050'],
                        ['deanery'=>'Bandra','name'=>'St Andrew','code'=>'400-050','address'=>'115, Hill Road, Bandra, Mumbai 400050'],
                        ['deanery'=>'Bandra','name'=>'St Anne','code'=>'400-050','address'=>'Pali Hill, Nargis Dutt Road, Bandra (West), Mumbai, Maharashtra 400050'],
                        ['deanery'=>'Bandra','name'=>'St Francis of Assisi','code'=>'400-050','address'=>'Kadeshwari Marg, Bandra, Mumbai 400050'],
                        ['deanery'=>'Bandra','name'=>'St Peter','code'=>'400-050','address'=>'Hill Road, Bandra, Mumbai 400050'],
                        ['deanery'=>'Bandra','name'=>'St Theresa','code'=>'400-050','address'=>'St Theresa Marg, T.P.S. III, Bandra, Mumbai 400050'],
                        ['deanery'=>'Bandra','name'=>'St Vincent De Paul','code'=>'400-052','address'=>'St Vincent De Paul Church, 20th Road, Khar West, Mumbai 400052'],
                        ['deanery'=>'Central Suburbs','name'=>'Our Lady of Health of Velankanni','code'=>'400-056','address'=>'Society Road, Irla, Mumbai 400056'],
                        ['deanery'=>'Central Suburbs','name'=>'St Joseph','code'=>'400-049','address'=>'Juhu, Mumbai 400049'],
                        ['deanery'=>'Central Suburbs','name'=>'Holy Cross','code'=>'400-049','address'=>'Gawde Road, Juhu-Tara, Mumbai 400049'],
                        ['deanery'=>'Central Surburbs','name'=>'Our Lady of Egypt','code'=>'400-029','address'=>'Kalina, Santa Cruz East, Mumbai 400029'],
                        ['deanery'=>'Central Suburbs','name'=>'Sacred Heart','code'=>'400-054','address'=>'Swami Vivekanand Road, Santa Cruz West, Mumbai 400054'],
                        ['deanery'=>'Central Suburbs','name'=>'St Anthony','code'=>'400-055','address'=>'Vakola, Santa Cruz East, Mumbai 400055'],
                        ['deanery'=>'Central Suburbs','name'=>'St Francis Xavier','code'=>'400-056','address'=>'Church Road, Vile Parle West, Mumbai 400056'],
                        ['deanery'=>'Andheri','name'=>'Holy Family','code'=>'400-093','address'=>'Andheri East, Mumbai 400093'],
                        ['deanery'=>'Andheri','name'=>'Sacred Heart','code'=>'400-093','address'=>'Mahakali Road, Andheri East, Mumbai 400093'],
                        ['deanery'=>'Andheri','name'=>'Good Shepherd','code'=>'400-053','address'=>'Four Bungalows Road, Andheri West, Mumbai 400053'],
                        ['deanery'=>'Andheri','name'=>'St Blaise','code'=>'400-058','address'=>'Caesar Road, Amboli, Andheri West, Mumbai 400058'],
                        ['deanery'=>'Andheri','name'=>'Infant Jesus','code'=>'400-060','address'=>'Off Western Express Highway, Shankarwadi, Jogeshwari East, Mumbai 400060'],
                        ['deanery'=>'Andheri','name'=>'Christ the King','code'=>'400-102','address'=>'Kranti Nagar, Behram Baug Road, Oshiwara, Jogeshwari West, Mumbai 400102'],
                        ['deanery'=>'Andheri','name'=>'St John the Evangelist','code'=>'400-059','address'=>'Church Road, Marol, Andheri East, Mumbai 400059'],
                        ['deanery'=>'Andheri','name'=>'St Vincent Pallotti','code'=>'400-059','address'=>'Vijay Nagar, Marol-Maroshi Road, Mumbai 400059'],
                        ['deanery'=>'Andheri','name'=>'Our Lady of Health','code'=>'400-099','address'=>'New International Cargo Complex, Sahar, Andheri East, Mumbai 400099'],
                        ['deanery'=>'Andheri','name'=>'Our Lady of Health','code'=>'400-061','address'=>'Yari Road, Versova, Andheri West, Mumbai 400061'],
                        ['deanery'=>'Borivli','name'=>'Christ the King','code'=>'400-066','address'=>'102, Namrata Building, 1st floor, Odhav Nagar, Borivli East, Mumbai 400066'],
                        ['deanery'=>'Borivli','name'=>'Our Lady of the Immaculate Conception','code'=>'400-103','address'=>'Mt. Poinsur, Borivli West, Mumbai 400103'],
                        ['deanery'=>'Borivli','name'=>'St John Bosco','code'=>'400-091','address'=>'Vazira Naka, L.T. Road, Borivli West, Mumbai 400091'],
                        ['deanery'=>'Borivli','name'=>'St Louis','code'=>'400-068','address'=>'Near Old Bridge, Y.T. Road, Dahisar West, Mumbai 400068'],
                        ['deanery'=>'Borivli','name'=>'St Joseph','code'=>'400-063','address'=>'002, A/46, Prashant, Sai Road, Gokuldham, Goregaon East, Mumbai 400063'],
                        ['deanery'=>'Borivli','name'=>'St Thomas','code'=>'400-063','address'=>'Church Road, Goregaon East, Mumbai 400063'],
                        ['deanery'=>'Borivli','name'=>'Our Lady of the Rosary','code'=>'400-062','address'=>'Mahatma Gandhi Road, Goregaon West, Mumbai 400062'],
                        ['deanery'=>'Borivli','name'=>'Nativity of Our Lord','code'=>'400-101','address'=>'C.T.S. 169, Akurli Road, Opp. Mahindra Yellow Gate, Kandivli East, Mumbai 400101'],
                        ['deanery'=>'Borivli','name'=>'Our Lady of the Assumption','code'=>'400-067','address'=>'Dahanukarwadi, Mahatma Gandhi Road, Kandivli West, Mumbai 400067'],
                        ['deanery'=>'Borivli','name'=>'Our Lady of the Sea','code'=>'400-095','address'=>'Madh Island, Malad, Mumbai 400095'],
                        ['deanery'=>'Borivli','name'=>'St Jude','code'=>'400-097','address'=>'Vaishet Pada, Triveni Nagar, Malad East, Mumbai, Maharashtra 400097'],
                        ['deanery'=>'Borivli','name'=>'Our Lady of Lourdes','code'=>'400-064','address'=>'Marve Road, Orlem, Malad West, Mumbai 400064'],
                        ['deanery'=>'Borivli','name'=>'St Anthony','code'=>'400-095','address'=>'Malwani, Malad West, Mumbai 400095'],
                        ['deanery'=>'Borivli','name'=>'Our Lady of the Forsaken','code'=>'400-095','address'=>'Off Malad-Marve Road, Block 7, Malwani Colony, Mumbai 400095'],
                        ['deanery'=>'Borivli','name'=>'Our Lady of Remedy','code'=>'400-067','address'=>'Poinsur, P.O. Kandivli, Mumbai 400067'],
                        ['deanery'=>'Kurla','name'=>'Mother Vellankanni','code'=>'400-088','address'=>'Sector 1, Jacob Johnson Marg, Near BMC Ground, Cheetah Camp, Mumbai 400088'],
                        ['deanery'=>'Kurla','name'=>'Our Lady of Perpetual Succour','code'=>'400-071','address'=>'St Anthony Road, Chembur, Mumbai 400071'],
                        ['deanery'=>'Kurla','name'=>'Infant Jesus','code'=>'400-075','address'=>'Pant Nagar,Ghatkopar East, Mumbai 400075'],
                        ['deanery'=>'Kurla','name'=>'St Jude','code'=>'400-072','address'=>'M.V. Marg, Andheri-Kurla Road, Jeri-Meri, Mumbai 400072'],
                        ['deanery'=>'Kurla','name'=>'Our Lady of Fatima','code'=>'400-086','address'=>'P.B. 9237, Kirol, Vidyavihar, Mumbai 400086'],
                        ['deanery'=>'Kurla','name'=>'Holy Cross','code'=>'400-070','address'=>'Fr Peter Pereira Marg, Kurla, Mumbai 400070'],
                        ['deanery'=>'Kurla','name'=>'St Joseph','code'=>'400-070','address'=>'New Mill Road, Kurla West, Mumbai 400070'],
                        ['deanery'=>'Kurla','name'=>'St Anthony','code'=>'400-088','address'=>'Mankhurd, P.O. Deonar, Mumbai 400088'],
                        ['deanery'=>'Kurla','name'=>'St Sebastian','code'=>'400-074','address'=>'Mahul Road, Marouli, Mumbai 400074'],
                        ['deanery'=>'Kurla','name'=>'Holy Family','code'=>'400-089','address'=>'Pestom Sagar, Road No.4, P.O. Tilaknagar, Chembur, Mumbai 400089'],
                        ['deanery'=>'Kurla','name'=>'St Anthony','code'=>'400-072','address'=>'Kherani Road, Saki Naka, Mumbai 400072'],
                        ['deanery'=>'Thane','name'=>'Our Lady of Fatima','code'=>'421-505','address'=>'Satchit, Ambernath West, Dt. Thane 421505'],
                        ['deanery'=>'Thane','name'=>'St Francis Xavier','code'=>'421-503','address'=>'D\'Souza Garden,Rameshwadi, Badlapur West, Dt. Thane 421503'],
                        ['deanery'=>'Thane','name'=>'Infant Jesus','code'=>'421-202','address'=>'Ganesh Nagar, Dombivli West, Dt.Thane 421202'],
                        ['deanery'=>'Thane','name'=>'St Anthony of Padua','code'=>'400-605','address'=>'Sushila Buildings, Block B/6, 2nd floor, Vikram Nagar, Kalwa, Dt. Thane 400605'],
                        ['deanery'=>'Thane','name'=>'Our Lady of Lourdes','code'=>'421-306','address'=>'Katemanavli, Kalyan East, Dt. Thane 421306'],
                        ['deanery'=>'Thane','name'=>'Our Lady of Lourdes','code'=>'421-301','address'=>'Murbad Road, Kalyan West, Dt. Thane 421301'],
                        ['deanery'=>'Thane','name'=>'St Francis Xavier','code'=>'400-042','address'=>'Church Road, Kanjurmarg East, Mumbai 400042'],
                        ['deanery'=>'Thane','name'=>'Our Lady of Fatima','code'=>'400-601','address'=>'Opp. Municipal Office, Majiwada, Dt. Thane 400601'],
                        ['deanery'=>'Thane','name'=>'St Pius X','code'=>'400-080','address'=>'Mulund West, Mumbai 400080'],
                        ['deanery'=>'Thane','name'=>'St Joseph','code'=>'400-612','address'=>'Behind Mumbra Police Station, Near Shanti Nagar, Anand Koliwada, Mumbra, Dt. Thane 400612'],
                        ['deanery'=>'Thane','name'=>'St Francis Xavier','code'=>'400-079','address'=>'4th Road, Parksite, Vikhroli West, Mumbai 400079'],
                        ['deanery'=>'Thane','name'=>'Our Lady of Mercy','code'=>'400-610','address'=>'Pokhran Road No.2, Near Blue Star Company, Thane 400610'],
                        ['deanery'=>'Thane','name'=>'Most Holy Trinity','code'=>'400-076','address'=>'Near I.I.T. Market, Powai, Mumbai 400076'],
                        ['deanery'=>'Thane','name'=>'St Anthony','code'=>'400-078','address'=>'Tembipada, Bhandup, Milind Nagar, Tembhipada, Bhandup West, Mumbai, 400078'],
                        ['deanery'=>'Thane','name'=>'St John the Baptist','code'=>'400-601','address'=>'Jambli Naka, L.B.S. Marg, Thane 400601'],
                        ['deanery'=>'Thane','name'=>'St Joseph','code'=>'400-079','address'=>'Station Road, Vikhroli West, Mumbai 400079'],
                        ['deanery'=>'Thane','name'=>'St Lawrence','code'=>'400-604','address'=>'Vasudev Balwant Phadke Road, D\'Souza Wadi, Wagle Estate, Dt. Thane 400604'],
                        ['deanery'=>'Bhayandar','name'=>'Divine Mercy','code'=>'401-105','address'=>'Ramdev Park Road, Near Ostwal Avenue Bhayandar East, Dt. Thane 401105'],
                        ['deanery'=>'Bhayandar','name'=>'Our Lady of Nazareth','code'=>'401-101','address'=>'Near Mira BHAYANDAR Nagarpalika, Bhayandar, Dt. Thane 401101'],
                        ['deanery'=>'Bhayandar','name'=>'St Andrew','code'=>'401-106','address'=>'Dongri-Chowk, P.O. Uttan, Dt. Thane 401106'],
                        ['deanery'=>'Bhayandar','name'=>'Our Lady of Bethlehem','code'=>'401-106','address'=>'Dongri, via Bhayandar, Dt. Thane 401106'],
                        ['deanery'=>'Bhayandar','name'=>'Holy Magi','code'=>'400-091','address'=>'Gorai village (Beyond the Creek), P.O. Borivli, Mumbai 400091'],
                        ['deanery'=>'Bhayandar','name'=>'St Jerome','code'=>'401-104','address'=>'P.O. Mira, Kashimira, Dt. Thane 401104'],
                        ['deanery'=>'Bhayandar','name'=>'Our Lady of Perpetual Succour','code'=>'400-095','address'=>'Manori, P.O. Kharodi, Mumbai 400095'],
                        ['deanery'=>'Bhayandar','name'=>'St Joseph','code'=>'401-107','address'=>'Krista Shanti Dham, St Joseph Chowk, Mira Road East, Dt. Thane 401107.'],
                        ['deanery'=>'Bhayandar','name'=>'Our Lady of the Sea','code'=>'401-106','address'=>'Uttan, Bhayandar West, Dt. Thane 401106'],
                        ['deanery'=>'Bhayandar','name'=>'Our Lady of Lourdes','code'=>'401-106','address'=>'Uttan-Pali, P.O.Uttan, Dt. Thane 401106'],
                        ['deanery'=>'Navi Mumbai','name'=>'St Theresa of the Child Jesus','code'=>'400-708','address'=>'Plot 24, Sector 10, Airoli, Navi Mumbai 400708'],
                        ['deanery'=>'Navi Mumbai','name'=>'St Joseph','code'=>'400-614','address'=>'Plot No.28, Sector 8B, C.B.D.- Belapur, Navi Mumbai 400614'],
                        ['deanery'=>'Navi Mumbai','name'=>'Our Lady of the Forsaken','code'=>'400-701','address'=>'Ghansoli Village, Building No. 446, THANE-Belapur Road, Navi Mumbai 400701'],
                        ['deanery'=>'Navi Mumbai','name'=>'Holy Spirit','code'=>'410-218','address'=>'Plot No.6, Sector 11, Kalamboli, Navi Mumbai 410218'],
                        ['deanery'=>'Navi Mumbai','name'=>'Divya Kripa','code'=>'410-210','address'=>'Plot No. 7, Sector 5, opp ITM Hostel, Kharghar, Navi Mumbai 410210'],
                        ['deanery'=>'Navi Mumbai','name'=>'St Francis De Sales','code'=>'400-709','address'=>'Plot No. 19-B/2 Sector 11, Koparkhairane, Navi Mumbai, 400709'],
                        ['deanery'=>'Navi Mumbai','name'=>'Our Lady of the Visitation','code'=>'400-706','address'=>'Seawoods West, Sector 42A, Nerul, Navi Mumbai, 400706'],
                        ['deanery'=>'Navi Mumbai','name'=>'St Francis Xavier','code'=>'410-206','address'=>'Behind Orion Mall (McDonald\'s side) & S.T. Depot, Near Samrat Hotel, Panvel 410206'],
                        ['deanery'=>'Navi Mumbai','name'=>'Christ the King','code'=>'410-222','address'=>'Vishwadeep Nagar, Reeswadi, Mohopada Post, Rasayani, Dt. Raigad 410222'],
                        ['deanery'=>'Navi Mumbai','name'=>'Good Shepherd','code'=>'400-705','address'=>'Plot No 51, Sector 5, Sanpada East, Navi Mumbai 400705'],
                        ['deanery'=>'Navi Mumbai','name'=>'Our Lady of the Purification','code'=>'400-702','address'=>'Gandhi Chowk, Rajpal Naka, Uran, Navi Mumbai, Raigad 400702'],
                        ['deanery'=>'Navi Mumbai','name'=>'Sacred Heart','code'=>'400-703','address'=>'Plot 67, Sector 9A, Vashi, Navi Mumbai 400703'],
                        ['deanery'=>'Raigad','name'=>'Mary of Nazareth','code'=>'402-201','address'=>'Chendre, Bypass Road, Near Petrol Pump, Alibag, Dt. Raigad 402201'],
                        ['deanery'=>'Raigad','name'=>'Our Lady of Fatima','code'=>'410-201','address'=>'Karjat West, Dt. Raigad 410201'],
                        ['deanery'=>'Raigad','name'=>'Holy Redeemer','code'=>'410-203','address'=>'Bhanwaj Road, Khopoli, Khalapur Taluka, Dt. Raigad 410203'],
                        ['deanery'=>'Raigad','name'=>'Our Lady of Mount Carmel','code'=>'402-202','address'=>'Korlai, via Revdanda, Dt. Raigad 402202'],
                        ['deanery'=>'Raigad','name'=>'St Francis Xavier','code'=>'402-301','address'=>'Jankalyan Trust, Sunderwadi, P.O. Box 7, P.O. Mahad, Dt. Raigad 402301'],
                        ['deanery'=>'Raigad','name'=>'Sacred Heart','code'=>'402-116','address'=>'Next to Varse Panchayat Office, P.O. Varse, Roha Taluka, Dt. Raigad, 402116'],
                        ['deanery'=>'Kurla','name'=>'Christ the King','code'=>'400-043','address'=>'Plot No. 46, P.O.Shivaji Nagar, Govandi, Mumbai 400043']
                    ];
                        ;

        Parish::insert($parishes);
    }
}
