<?php

namespace Modules\Members\Database\Seeders;

use Modules\Members\Models\Parish;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ParishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $parishes = [
            ['deanery' => 'Thane', 'name' => 'Our Lady of Perpetual Succour', 'code' => '421004', 'address' => 'Block No A528, Room No 1056, Ulhasnagar, Dt. Thane 421004', 'town' => 'Ulhasnagar'],
            ['deanery' => 'South Mumbai', 'name' => 'Cathedral of the Holy Name', 'code' => '400001', 'address' => '19, Nathalal Parekh Marg, Mumbai 400001', 'town' => 'Colaba'],
            ['deanery' => 'South Mumbai', 'name' => 'Our Lady of Health', 'code' => '400002', 'address' => 'Dr. Viegas Street, Cavel, Mumbai 400002', 'town' => 'Cavel'],
            ['deanery' => 'South Mumbai', 'name' => 'Our Lady of Glory', 'code' => '400027', 'address' => 'Sant Savta Marg, Byculla, Mumbai 400027', 'town' => 'Byculla'],
            ['deanery' => 'South Mumbai', 'name' => 'St Stephen', 'code' => '400036', 'address' => '1, L. Jagmohandas Marg, Cumballa Hill, Mumbai 400036', 'town' => 'Cumbulla Hill'],
            ['deanery' => 'South Mumbai', 'name' => 'St Joseph', 'code' => '400005', 'address' => 'Robert Road, Colaba, Mumbai 400005', 'town' => 'Colaba'],
            ['deanery' => 'South Mumbai', 'name' => 'St Francis Xavier', 'code' => '400002', 'address' => 'St. Francis Xavier Street, Thakurdwar, Dabul, Mumbai 400002', 'town' => 'Dabul'],
            ['deanery' => 'South Mumbai', 'name' => 'St John the Evangelist', 'code' => '400001', 'address' => '8, Dr Sunderlal Bahl Path, Ballard Estate, Fort, Mumbai 400001', 'town' => 'Fort'],
            ['deanery' => 'South Mumbai', 'name' => 'St Teresa', 'code' => '400004', 'address' => '252, Rajaram Mohan Roy Road, Girgaum, Mumbai 400004', 'town' => 'GIrgaul'],
            ['deanery' => 'South Mumbai', 'name' => 'St Ignatius', 'code' => '400003', 'address' => '203, Kazi Syed Street, Mandvi, Mumbai 400003', 'town' => 'Mandvi'],
            ['deanery' => 'South Mumbai', 'name' => 'Our Lady of the Rosary', 'code' => '400010', 'address' => 'Dockyard Road, Mazagaon, Mumbai 400010', 'town' => 'Mazagaon'],
            ['deanery' => 'South Mumbai', 'name' => 'St Anne', 'code' => '400010', 'address' => 'Dhody Marg, Mazagaon, Mumbai 400010', 'town' => 'Mazagaon'],
            ['deanery' => 'South Mumbai', 'name' => 'Our Lady of Dolours', 'code' => '400002', 'address' => 'Dr. Cawasji Hormusji Street, New Sonapur, Marine Lines, Mumbai 400002', 'town' => 'Marine Lines'],
            ['deanery' => 'South Mumbai', 'name' => 'St Joseph', 'code' => '400009', 'address' => 'St Joseph Chowk, Nowrojee Hill Road No.5, Umerkhadi, Mumbai 400009', 'town' => 'Umerkhadi'],
            ['deanery' => 'North Mumbai', 'name' => 'St Paul', 'code' => '400014', 'address' => '205, Dr. Ambedkar Road, Dadar, Mumbai 400014', 'town' => 'Dadar-E'],
            ['deanery' => 'North Mumbai', 'name' => 'Our Lady of Salvation', 'code' => '400028', 'address' => 'S.K. Bole Road, Dadar, Mumbai 400028', 'town' => 'Dadar-W'],
            ['deanery' => 'North Mumbai', 'name' => 'St Anthony', 'code' => '400017', 'address' => 'Plot No. 890C, Dharavi Main Road, Near Post Office, Dharavi, Mumbai 400017', 'town' => 'Daravi'],
            ['deanery' => 'North Mumbai', 'name' => 'St Ignatius', 'code' => '400011', 'address' => 'Sane Guruji Road, Jacob Circle, Mumbai 400011', 'town' => 'Jacob Circle'],
            ['deanery' => 'North Mumbai', 'name' => 'Holy Cross', 'code' => '400013', 'address' => 'Senapati Bapat Marg, Lower Parel, Mumbai 400013', 'town' => 'Lower Parel'],
            ['deanery' => 'North Mumbai', 'name' => 'Our Lady of Victories', 'code' => '400016', 'address' => 'Lady Jamshedji Road, Mahim, Mumbai 400016', 'town' => 'Mahim'],
            ['deanery' => 'North Mumbai', 'name' => 'St Michael', 'code' => '400016', 'address' => 'Lady Jamshedji Road, Mahim, Mumbai 400016', 'town' => 'Mahim'],
            ['deanery' => 'North Mumbai', 'name' => 'Our Lady of Fatima', 'code' => '400015', 'address' => 'Golanji Hill Road, Sewri, Mumbai 400015', 'town' => 'Sewri'],
            ['deanery' => 'North Mumbai', 'name' => 'Our Lady of Good Counsel', 'code' => '400022', 'address' => 'Near Railway Station, Sion, Mumbai 400022', 'town' => 'Sion'],
            ['deanery' => 'North Mumbai', 'name' => 'Our Lady of Lourdes', 'code' => '400022', 'address' => 'Bhaudaji Extension Road, Sion, Mumbai 400022', 'town' => 'Sion'],
            ['deanery' => 'North Mumbai', 'name' => 'St Dominic Savio', 'code' => '400037', 'address' => 'Wadala East, Mumbai 400037', 'town' => 'Wadala-E'],
            ['deanery' => 'North Mumbai', 'name' => 'Our Lady of Dolours', 'code' => '400031', 'address' => 'David Barretto Road, Wadala, Mumbai 400031', 'town' => 'Wadala'],
            ['deanery' => 'North Mumbai', 'name' => 'Sacred Heart', 'code' => '400030', 'address' => '26, Sasmira Marg, Worli, Mumbai 400030', 'town' => 'Worli'],
            ['deanery' => 'Bandra', 'name' => 'St Joseph the Worker', 'code' => '400051', 'address' => 'Bandra East, Mumbai 400051', 'town' => 'Bandra-E'],
            ['deanery' => 'Bandra', 'name' => 'Our Lady of Mount Carmel', 'code' => '400050', 'address' => '81A, Chapel Road, Bandra, Mumbai 400050', 'town' => 'Bandra-W'],
            ['deanery' => 'Bandra', 'name' => 'St Andrew', 'code' => '400050', 'address' => '115, Hill Road, Bandra, Mumbai 400050', 'town' => 'Bandra-W'],
            ['deanery' => 'Bandra', 'name' => 'St Anne', 'code' => '400050', 'address' => 'Pali Hill, Nargis Dutt Road, Bandra (West), Mumbai, Maharashtra 400050', 'town' => 'Bandra-W'],
            ['deanery' => 'Bandra', 'name' => 'St Francis of Assisi', 'code' => '400050', 'address' => 'Kadeshwari Marg, Bandra, Mumbai 400050', 'town' => 'Bandra-W'],
            ['deanery' => 'Bandra', 'name' => 'St Peter', 'code' => '400050', 'address' => 'Hill Road, Bandra, Mumbai 400050', 'town' => 'Bandra-W'],
            ['deanery' => 'Bandra', 'name' => 'St Theresa', 'code' => '400050', 'address' => 'St Theresa Marg, T.P.S. III, Bandra, Mumbai 400050', 'town' => 'Bandra-W'],
            ['deanery' => 'Bandra', 'name' => 'St Vincent De Paul', 'code' => '400052', 'address' => 'St Vincent De Paul Church, 20th Road, Khar West, Mumbai 400052', 'town' => 'Khar-W'],
            ['deanery' => 'Central Suburbs', 'name' => 'Our Lady of Health of Velankanni', 'code' => '400056', 'address' => 'Society Road, Irla, Mumbai 400056', 'town' => 'Irla'],
            ['deanery' => 'Central Suburbs', 'name' => 'St Joseph', 'code' => '400049', 'address' => 'Juhu, Mumbai 400049', 'town' => 'Juhu'],
            ['deanery' => 'Central Suburbs', 'name' => 'Holy Cross', 'code' => '400049', 'address' => 'Gawde Road, JuhuTara, Mumbai 400049', 'town' => 'Juhu'],
            ['deanery' => 'Central Surburbs', 'name' => 'Our Lady of Egypt', 'code' => '400029', 'address' => 'Kalina, Santa Cruz East, Mumbai 400029', 'town' => 'Santa Cruz-E'],
            ['deanery' => 'Central Suburbs', 'name' => 'Sacred Heart', 'code' => '400054', 'address' => 'Swami Vivekanand Road, Santa Cruz West, Mumbai 400054', 'town' => 'Santa Cruz-W'],
            ['deanery' => 'Central Suburbs', 'name' => 'St Anthony', 'code' => '400055', 'address' => 'Vakola, Santa Cruz East, Mumbai 400055', 'town' => 'Santa Cruz-E'],
            ['deanery' => 'Central Suburbs', 'name' => 'St Francis Xavier', 'code' => '400056', 'address' => 'Church Road, Vile Parle West, Mumbai 400056', 'town' => 'Vile Parle-W'],
            ['deanery' => 'Andheri', 'name' => 'Holy Family', 'code' => '400093', 'address' => 'Andheri East, Mumbai 400093', 'town' => 'Andheri-E'],
            ['deanery' => 'Andheri', 'name' => 'Sacred Heart', 'code' => '400093', 'address' => 'Mahakali Road, Andheri East, Mumbai 400093', 'town' => 'Andheri-E'],
            ['deanery' => 'Andheri', 'name' => 'Good Shepherd', 'code' => '400053', 'address' => 'Four Bungalows Road, Andheri West, Mumbai 400053', 'town' => 'Andheri-W'],
            ['deanery' => 'Andheri', 'name' => 'St Blaise', 'code' => '400058', 'address' => 'Caesar Road, Amboli, Andheri West, Mumbai 400058', 'town' => 'Andheri-W'],
            ['deanery' => 'Andheri', 'name' => 'Infant Jesus', 'code' => '400060', 'address' => 'Off Western Express Highway, Shankarwadi, Jogeshwari East, Mumbai 400060', 'town' => 'Joseshwari-E'],
            ['deanery' => 'Andheri', 'name' => 'Christ the King', 'code' => '400102', 'address' => 'Kranti Nagar, Behram Baug Road, Oshiwara, Jogeshwari West, Mumbai 400102', 'town' => 'Joseshwari-W'],
            ['deanery' => 'Andheri', 'name' => 'St John the Evangelist', 'code' => '400059', 'address' => 'Church Road, Marol, Andheri East, Mumbai 400059', 'town' => 'Andheri-E'],
            ['deanery' => 'Andheri', 'name' => 'St Vincent Pallotti', 'code' => '400059', 'address' => 'Vijay Nagar, MarolMaroshi Road, Mumbai 400059', 'town' => 'Andheri-E'],
            ['deanery' => 'Andheri', 'name' => 'Our Lady of Health', 'code' => '400099', 'address' => 'New International Cargo Complex, Sahar, Andheri East, Mumbai 400099', 'town' => 'Andheri-E'],
            ['deanery' => 'Andheri', 'name' => 'Our Lady of Health', 'code' => '400061', 'address' => 'Yari Road, Versova, Andheri West, Mumbai 400061', 'town' => 'Andheri-W'],
            ['deanery' => 'Borivli', 'name' => 'Christ the King', 'code' => '400066', 'address' => '102, Namrata Building, 1st floor, Odhav Nagar, Borivli East, Mumbai 400066', 'town' => 'Borivli-E'],
            ['deanery' => 'Borivli', 'name' => 'Our Lady of the Immaculate Conception', 'code' => '400103', 'address' => 'Mt. Poinsur, Borivli West, Mumbai 400103', 'town' => 'Borivli-W'],
            ['deanery' => 'Borivli', 'name' => 'St John Bosco', 'code' => '400091', 'address' => 'Vazira Naka, L.T. Road, Borivli West, Mumbai 400091', 'town' => 'Borivli-W'],
            ['deanery' => 'Borivli', 'name' => 'St Louis', 'code' => '400068', 'address' => 'Near Old Bridge, Y.T. Road, Dahisar West, Mumbai 400068', 'town' => 'Dahisar-W'],
            ['deanery' => 'Borivli', 'name' => 'St Joseph', 'code' => '400063', 'address' => '002, A/46, Prashant, Sai Road, Gokuldham, Goregaon East, Mumbai 400063', 'town' => 'Goregaon-E'],
            ['deanery' => 'Borivli', 'name' => 'St Thomas', 'code' => '400063', 'address' => 'Church Road, Goregaon East, Mumbai 400063', 'town' => 'Goregaon-E'],
            ['deanery' => 'Borivli', 'name' => 'Our Lady of the Rosary', 'code' => '400062', 'address' => 'Mahatma Gandhi Road, Goregaon West, Mumbai 400062', 'town' => 'Goregaon-W'],
            ['deanery' => 'Borivli', 'name' => 'Nativity of Our Lord', 'code' => '400101', 'address' => 'C.T.S. 169, Akurli Road, Opp. Mahindra Yellow Gate, Kandivli East, Mumbai 400101', 'town' => 'Kandivli-E'],
            ['deanery' => 'Borivli', 'name' => 'Our Lady of the Assumption', 'code' => '400067', 'address' => 'Dahanukarwadi, Mahatma Gandhi Road, Kandivli West, Mumbai 400067', 'town' => 'Kandivli-W'],
            ['deanery' => 'Borivli', 'name' => 'Our Lady of the Sea', 'code' => '400095', 'address' => 'Madh Island, Malad, Mumbai 400095', 'town' => 'Malad-W'],
            ['deanery' => 'Borivli', 'name' => 'St Jude', 'code' => '400097', 'address' => 'Vaishet Pada, Triveni Nagar, Malad East, Mumbai, Maharashtra 400097', 'town' => 'Malad-E'],
            ['deanery' => 'Borivli', 'name' => 'Our Lady of Lourdes', 'code' => '400064', 'address' => 'Marve Road, Orlem, Malad West, Mumbai 400064', 'town' => 'Malad-W'],
            ['deanery' => 'Borivli', 'name' => 'St Anthony', 'code' => '400095', 'address' => 'Malwani, Malad West, Mumbai 400095', 'town' => 'Malad-W'],
            ['deanery' => 'Borivli', 'name' => 'Our Lady of the Forsaken', 'code' => '400095', 'address' => 'Off MaladMarve Road, Block 7, Malwani Colony, Mumbai 400095', 'town' => 'Malad-W'],
            ['deanery' => 'Borivli', 'name' => 'Our Lady of Remedy', 'code' => '400067', 'address' => 'Poinsur, P.O. Kandivli, Mumbai 400067', 'town' => 'Kandivli-W'],
            ['deanery' => 'Kurla', 'name' => 'Mother Vellankanni', 'code' => '400088', 'address' => 'Sector 1, Jacob Johnson Marg, Near BMC Ground, Cheetah Camp, Mumbai 400088', 'town' => 'Cheetah Camp'],
            ['deanery' => 'Kurla', 'name' => 'Our Lady of Perpetual Succour', 'code' => '400071', 'address' => 'St Anthony Road, Chembur, Mumbai 400071', 'town' => 'Chembur'],
            ['deanery' => 'Kurla', 'name' => 'Infant Jesus', 'code' => '400075', 'address' => 'Pant Nagar,Ghatkopar East, Mumbai 400075', 'town' => 'Ghatkopar-E'],
            ['deanery' => 'Kurla', 'name' => 'St Jude', 'code' => '400072', 'address' => 'M.V. Marg, AndheriKurla Road, JeriMeri, Mumbai 400072', 'town' => 'Jeri Meri'],
            ['deanery' => 'Kurla', 'name' => 'Our Lady of Fatima', 'code' => '400086', 'address' => 'P.B. 9237, Kirol, Vidyavihar, Mumbai 400086', 'town' => 'Vidyavihar'],
            ['deanery' => 'Kurla', 'name' => 'Holy Cross', 'code' => '400070', 'address' => 'Fr Peter Pereira Marg, Kurla, Mumbai 400070', 'town' => 'Kurla'],
            ['deanery' => 'Kurla', 'name' => 'St Joseph', 'code' => '400070', 'address' => 'New Mill Road, Kurla West, Mumbai 400070', 'town' => 'Kurla-W'],
            ['deanery' => 'Kurla', 'name' => 'St Anthony', 'code' => '400088', 'address' => 'Mankhurd, P.O. Deonar, Mumbai 400088', 'town' => 'Deonar'],
            ['deanery' => 'Kurla', 'name' => 'St Sebastian', 'code' => '400074', 'address' => 'Mahul Road, Marouli, Mumbai 400074', 'town' => 'Marouli'],
            ['deanery' => 'Kurla', 'name' => 'Holy Family', 'code' => '400089', 'address' => 'Pestom Sagar, Road No.4, P.O. Tilaknagar, Chembur, Mumbai 400089', 'town' => 'Chembur'],
            ['deanery' => 'Kurla', 'name' => 'St Anthony', 'code' => '400072', 'address' => 'Kherani Road, Saki Naka, Mumbai 400072', 'town' => 'Saki Naka'],
            ['deanery' => 'Thane', 'name' => 'Our Lady of Fatima', 'code' => '421505', 'address' => 'Satchit, Ambernath West, Dt. Thane 421505', 'town' => 'Ambernath-W'],
            ['deanery' => 'Thane', 'name' => 'St Francis Xavier', 'code' => '421503', 'address' => 'D\'Souza Garden,Rameshwadi, Badlapur West, Dt. Thane 421503', 'town' => 'Badlapur-W'],
            ['deanery' => 'Thane', 'name' => 'Infant Jesus', 'code' => '421202', 'address' => 'Ganesh Nagar, Dombivli West, Dt.Thane 421202', 'town' => 'Dombivli-W'],
            ['deanery' => 'Thane', 'name' => 'St Anthony of Padua', 'code' => '400605', 'address' => 'Sushila Buildings, Block B/6, 2nd floor, Vikram Nagar, Kalwa, Dt. Thane 400605', 'town' => 'Kalwa'],
            ['deanery' => 'Thane', 'name' => 'Our Lady of Lourdes', 'code' => '421306', 'address' => 'Katemanavli, Kalyan East, Dt. Thane 421306', 'town' => 'Kalyan-E'],
            ['deanery' => 'Thane', 'name' => 'Our Lady of Lourdes', 'code' => '421301', 'address' => 'Murbad Road, Kalyan West, Dt. Thane 421301', 'town' => 'Kalyan-W'],
            ['deanery' => 'Thane', 'name' => 'St Francis Xavier', 'code' => '400042', 'address' => 'Church Road, Kanjurmarg East, Mumbai 400042', 'town' => 'Kanjurmarg-E'],
            ['deanery' => 'Thane', 'name' => 'Our Lady of Fatima', 'code' => '400601', 'address' => 'Opp. Municipal Office, Majiwada, Dt. Thane 400601', 'town' => 'Majiwada'],
            ['deanery' => 'Thane', 'name' => 'St Pius X', 'code' => '400080', 'address' => 'Mulund West, Mumbai 400080', 'town' => 'Mulund-W'],
            ['deanery' => 'Thane', 'name' => 'St Joseph', 'code' => '400612', 'address' => 'Behind Mumbra Police Station, Near Shanti Nagar, Anand Koliwada, Mumbra, Dt. Thane 400612', 'town' => 'Mumbra'],
            ['deanery' => 'Thane', 'name' => 'St Francis Xavier', 'code' => '400079', 'address' => '4th Road, Parksite, Vikhroli West, Mumbai 400079', 'town' => 'Vikhroli-W'],
            ['deanery' => 'Thane', 'name' => 'Our Lady of Mercy', 'code' => '400610', 'address' => 'Pokhran Road No.2, Near Blue Star Company, Thane 400610', 'town' => 'Pokhran'],
            ['deanery' => 'Thane', 'name' => 'Most Holy Trinity', 'code' => '400076', 'address' => 'Near I.I.T. Market, Powai, Mumbai 400076', 'town' => 'Powai'],
            ['deanery' => 'Thane', 'name' => 'St Anthony', 'code' => '400078', 'address' => 'Tembipada, Bhandup, Milind Nagar, Tembhipada, Bhandup West, Mumbai, 400078', 'town' => 'Bhandup-W'],
            ['deanery' => 'Thane', 'name' => 'St John the Baptist', 'code' => '400601', 'address' => 'Jambli Naka, L.B.S. Marg, Thane 400601', 'town' => 'Jambli Naka'],
            ['deanery' => 'Thane', 'name' => 'St Joseph', 'code' => '400079', 'address' => 'Station Road, Vikhroli West, Mumbai 400079', 'town' => 'Vikhroli-W'],
            ['deanery' => 'Thane', 'name' => 'St Lawrence', 'code' => '400604', 'address' => 'Vasudev Balwant Phadke Road, D\'Souza Wadi, Wagle Estate, Dt. Thane 400604', 'town' => 'Wagle Estate'],
            ['deanery' => 'Bhayandar', 'name' => 'Divine Mercy', 'code' => '401105', 'address' => 'Ramdev Park Road, Near Ostwal Avenue Bhayandar East, Dt. Thane 401105', 'town' => 'Bhayander-E'],
            ['deanery' => 'Bhayandar', 'name' => 'Our Lady of Nazareth', 'code' => '401101', 'address' => 'Near Mira BHAYANDAR Nagarpalika, Bhayandar, Dt. Thane 401101', 'town' => 'Bhayander'],
            ['deanery' => 'Bhayandar', 'name' => 'St Andrew', 'code' => '401106', 'address' => 'DongriChowk, P.O. Uttan, Dt. Thane 401106', 'town' => 'Uttan'],
            ['deanery' => 'Bhayandar', 'name' => 'Our Lady of Bethlehem', 'code' => '401106', 'address' => 'Dongri, via Bhayandar, Dt. Thane 401106', 'town' => 'Bhayander-E'],
            ['deanery' => 'Bhayandar', 'name' => 'Holy Magi', 'code' => '400091', 'address' => 'Gorai village (Beyond the Creek), P.O. Borivli, Mumbai 400091', 'town' => 'Borivli'],
            ['deanery' => 'Bhayandar', 'name' => 'St Jerome', 'code' => '401104', 'address' => 'P.O. Mira, Kashimira, Dt. Thane 401104', 'town' => 'Kashmira'],
            ['deanery' => 'Bhayandar', 'name' => 'Our Lady of Perpetual Succour', 'code' => '400095', 'address' => 'Manori, P.O. Kharodi, Mumbai 400095', 'town' => 'Kharodu'],
            ['deanery' => 'Bhayandar', 'name' => 'St Joseph', 'code' => '401107', 'address' => 'Krista Shanti Dham, St Joseph Chowk, Mira Road East, Dt. Thane 401107.', 'town' => 'Mira Road-E'],
            ['deanery' => 'Bhayandar', 'name' => 'Our Lady of the Sea', 'code' => '401106', 'address' => 'Uttan, Bhayandar West, Dt. Thane 401106', 'town' => 'Bhayander-W'],
            ['deanery' => 'Bhayandar', 'name' => 'Our Lady of Lourdes', 'code' => '401106', 'address' => 'UttanPali, P.O.Uttan, Dt. Thane 401106', 'town' => 'Uttan'],
            ['deanery' => 'Navi Mumbai', 'name' => 'St Theresa of the Child Jesus', 'code' => '400708', 'address' => 'Plot 24, Sector 10, Airoli, Navi Mumbai 400708', 'town' => 'Airoli'],
            ['deanery' => 'Navi Mumbai', 'name' => 'St Joseph', 'code' => '400614', 'address' => 'Plot No.28, Sector 8B, C.B.D. Belapur, Navi Mumbai 400614', 'town' => 'Belapur'],
            ['deanery' => 'Navi Mumbai', 'name' => 'Our Lady of the Forsaken', 'code' => '400701', 'address' => 'Ghansoli Village, Building No. 446, THANEBelapur Road, Navi Mumbai 400701', 'town' => 'Ghansoli'],
            ['deanery' => 'Navi Mumbai', 'name' => 'Holy Spirit', 'code' => '410218', 'address' => 'Plot No.6, Sector 11, Kalamboli, Navi Mumbai 410218', 'town' => 'Kalamboli'],
            ['deanery' => 'Navi Mumbai', 'name' => 'Divya Kripa', 'code' => '410210', 'address' => 'Plot No. 7, Sector 5, opp ITM Hostel, Kharghar, Navi Mumbai 410210', 'town' => 'Kharghar'],
            ['deanery' => 'Navi Mumbai', 'name' => 'St Francis De Sales', 'code' => '400709', 'address' => 'Plot No. 19B/2 Sector 11, Koparkhairane, Navi Mumbai, 400709', 'town' => 'Koparkhairane'],
            ['deanery' => 'Navi Mumbai', 'name' => 'Our Lady of the Visitation', 'code' => '400706', 'address' => 'Seawoods West, Sector 42A, Nerul, Navi Mumbai, 400706', 'town' => 'Nerul'],
            ['deanery' => 'Navi Mumbai', 'name' => 'St Francis Xavier', 'code' => '410206', 'address' => 'Behind Orion Mall (McDonald\'s side) & S.T. Depot, Near Samrat Hotel, Panvel 410206', 'town' => 'Panvel'],
            ['deanery' => 'Navi Mumbai', 'name' => 'Christ the King', 'code' => '410222', 'address' => 'Vishwadeep Nagar, Reeswadi, Mohopada Post, Rasayani, Dt. Raigad 410222', 'town' => 'Rasayani'],
            ['deanery' => 'Navi Mumbai', 'name' => 'Good Shepherd', 'code' => '400705', 'address' => 'Plot No 51, Sector 5, Sanpada East, Navi Mumbai 400705', 'town' => 'Sanpada-E'],
            ['deanery' => 'Navi Mumbai', 'name' => 'Our Lady of the Purification', 'code' => '400702', 'address' => 'Gandhi Chowk, Rajpal Naka, Uran, Navi Mumbai, Raigad 400702', 'town' => 'Uran'],
            ['deanery' => 'Navi Mumbai', 'name' => 'Sacred Heart', 'code' => '400703', 'address' => 'Plot 67, Sector 9A, Vashi, Navi Mumbai 400703', 'town' => 'Vashi'],
            ['deanery' => 'Raigad', 'name' => 'Mary of Nazareth', 'code' => '402201', 'address' => 'Chendre, Bypass Road, Near Petrol Pump, Alibag, Dt. Raigad 402201', 'town' => 'Alibag'],
            ['deanery' => 'Raigad', 'name' => 'Our Lady of Fatima', 'code' => '410201', 'address' => 'Karjat West, Dt. Raigad 410201', 'town' => 'Karjat-W'],
            ['deanery' => 'Raigad', 'name' => 'Holy Redeemer', 'code' => '410203', 'address' => 'Bhanwaj Road, Khopoli, Khalapur Taluka, Dt. Raigad 410203', 'town' => 'Khalapur'],
            ['deanery' => 'Raigad', 'name' => 'Our Lady of Mount Carmel', 'code' => '402202', 'address' => 'Korlai, via Revdanda, Dt. Raigad 402202', 'town' => 'Revdanda'],
            ['deanery' => 'Raigad', 'name' => 'St Francis Xavier', 'code' => '402301', 'address' => 'Jankalyan Trust, Sunderwadi, P.O. Box 7, P.O. Mahad, Dt. Raigad 402301', 'town' => 'Mahad'],
            ['deanery' => 'Raigad', 'name' => 'Sacred Heart', 'code' => '402116', 'address' => 'Next to Varse Panchayat Office, P.O. Varse, Roha Taluka, Dt. Raigad, 402116', 'town' => 'Varse'],
            ['deanery' => 'Kurla', 'name' => 'Christ the King', 'code' => '400043', 'address' => 'Plot No. 46, P.O.Shivaji Nagar, Govandi, Mumbai 400043', 'town' => 'Govandi'],
        ];


        Parish::insert($parishes);
    }
}
